apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager-pv
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: alertmanager
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # PVC에 storageClass가 명시되지 않았으므로, 빈 문자열로 설정
  hostPath:
    path: /prom/data # 노드에 실제로 존재하는 경로를 지정해야 함
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - node1.example.com  # PV가 바인딩될 노드 이름을 지정
                - node2.example.com

